### ISSUE TITLE
Quick Reply Reloaded

### ISSUE THREAD

**Issue by Galixte** [cabot/quickreplytoggle#2]
Hi @cabot & @LavIgor,

could you take a look, please about the compatibility with https://github.com/BoardTools/QuickReply/tree/develop-2.x (2.0.0 version)?

https://www.phpbb.com/customise/db/extension/quick_reply_toggle/support/topic/173091?p=573051#p573051

**Comment by lavigor** [comment]
@Galixte the idea was to have the old compatibility when quick reply form is in 'standard' mode.
'Fixed' form mode disables quick reply toggle feature because of the implementation.

**Comment by Galixte** [comment]
@lavigor, ok i understand now, thanks!

Maybe @cabot,  could you add the possibility to activate the quick reply toggle functionality for each forum? Or, could you share a css/js tip to isolate forums where activate the quick reply toggle feature?

**Comment by Galixte** [comment]
Fixed: http://www.phpbb-fr.com/customise/db/extension/quick_reply_toggle/support/affichage_de_la_r%C3%A9ponse_rapide_quick_reply_reloaded_v2.0.0-t_1677-p_5376#p5376, thanks to @cabot!
